version: '3'
services:
  quotes:
    build: ./
    image: quotes-front-end
    container_name: quotes-front-end
    ports: 
      - "9000:80"
    environment: 
      - SERVER_ADDRESS=0.0.0.0:8080/quotes
    volumes:
      - ./:/usr/local/apache2/htdocs
  quotesmock:
    image: toroinvestimentos/quotesmock
    ports:
      - "8080:8080"
